mission_node:
  ros__parameters:
    mode: 1  # 0: manual, 1: auto
    waypoints:
      wp1:
        latitude: 30.0812120422
        longitude: 31.2961983329
      wp2:
        latitude: 30.0811119783  
        longitude: 31.2962010261 
      wp3:
        latitude: 30.081102905   
        longitude: 31.2960926525
