/*
 * bridge_c_api.h — Pure C interface for main.c to call the C++ bridge
 *
 * WHY THIS FILE EXISTS:
 *   main.c is a C file generated by CubeMX. It cannot include
 *   stm32_bridge.hpp because that file contains C++ syntax (classes,
 *   nullptr, etc.) which the C compiler cannot parse.
 *
 *   This header declares only the three C-linkage functions that
 *   main.c needs. No C++ syntax anywhere here.
 *
 *   stm32_bridge.cpp defines all three functions inside extern "C" {}
 *   so the linker connects them correctly across the C/C++ boundary.
 *
 * USAGE in main.c:
 *   #include "bridge_c_api.h"
 *
 *   // In USER CODE BEGIN 2:
 *   Bridge_Init();
 *
 *   // In while(1) USER CODE BEGIN 3:
 *   Bridge_Update();
 */

#ifndef BRIDGE_C_API_H
#define BRIDGE_C_API_H

#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

    /*
     * Bridge_Init — call once after all peripherals are initialised
     * Seeds the watchdog timer and sets the initial parser state.
     * Call AFTER MX_USB_DEVICE_Init() so USB is ready.
     */
    void Bridge_Init(void);

    /*
     * Bridge_Update — call every iteration of the main while(1) loop
     * Does three things in order:
     *   1. read_message()       — parse pending ring buffer bytes
     *   2. CheckWatchdog()      — trigger e-stop if heartbeat timed out
     *   3. Timed TX             — send IMU/Encoders at 50Hz, GPS/Status at 10Hz
     */
    void Bridge_Update(void);

    /*
     * STM32Bridge_PushBytes — called from CDC_Receive_FS in usbd_cdc_if.c
     * Copies received USB bytes into the ring buffer.
     * This is the ISR-side hook — must be fast, no parsing.
     */
    void STM32Bridge_PushBytes(const uint8_t *buf, uint32_t len);

#ifdef __cplusplus
}
#endif

#endif /* BRIDGE_C_API_H */
