/*
 * stm32_bridge.hpp — STM32Bridge class declaration
 *
 * WHAT THIS FILE DOES:
 *   Declares the STM32Bridge class that owns the entire USB CDC
 *   communication layer: ring buffer, parser state machine,
 *   watchdog, and transmit functions.
 *
 * INCLUDE RULES:
 *   - Include only in .cpp files, never in .c files
 *   - main.c uses bridge_c_api.h instead
 *   - usbd_cdc_if.c uses an inline extern declaration
 *
 * ARCHITECTURE:
 *
 *   USB ISR (CDC_Receive_FS)
 *       │
 *       ▼  calls STM32Bridge_PushBytes()
 *   PushBytesFromISR() — ring buffer write, nothing else
 *       │
 *   main loop calls Bridge_Update() every iteration
 *       │
 *       ▼
 *   read_message() — state machine parser
 *       └── STATE_SYNC → STATE_ID → STATE_LEN → STATE_PAYLOAD → STATE_CRC
 *               └── CRC pass → dispatch switch → apply motor cmd / feed watchdog
 *       │
 *   CheckWatchdog() — 500ms heartbeat timeout → ExecuteSafeStop()
 *       │
 *   Timed TX — IMU+Encoders at 50Hz, GPS+Status at 10Hz
 */

#ifndef STM32_BRIDGE_HPP
#define STM32_BRIDGE_HPP

/*
 * main.h is generated by CubeMX. It pulls in:
 *   - stm32f4xx_hal.h  (HAL_GetTick, HAL_GPIO_WritePin, HAL_Delay)
 *   - All peripheral handles (hi2c1, huart2, etc.)
 *   - GPIO_PIN_x and GPIOB/GPIOA defines
 * Do NOT include stm32f4xx_hal.h separately — main.h handles it.
 */
#include "main.h"

/*
 * messages.h is pure C — safe to include here.
 * Gives us: payload structs, MSG_* defines, build_frame(), crc8().
 */
#include "messages.h"

#include <stdint.h>

/* ── Class definition ────────────────────────────────────────────────── */
class STM32Bridge
{
public:
    STM32Bridge();

    /*
     * Init — seed watchdog timer, set parser to WAIT_SYNC
     * Call once after MX_USB_DEVICE_Init() in main.c
     */
    void Init();

    /*
     * PushBytesFromISR — called from CDC_Receive_FS USB interrupt
     * RULES: copy bytes into ring buffer ONLY.
     *        No parsing, no function calls, no blocking.
     */
    void PushBytesFromISR(const uint8_t *buf, uint32_t len);

    /*
     * read_message — parse ring buffer bytes, dispatch on CRC pass
     * Call every main loop iteration via Bridge_Update().
     */
    void read_message();

    /*
     * CheckWatchdog — compare HAL_GetTick() against last heartbeat
     * If silence > TIMEOUT_MS → calls ExecuteSafeStop().
     * Call every main loop iteration via Bridge_Update().
     */
    void CheckWatchdog();

    /*
     * SendPacket — build and transmit one framed message
     * debug_mode=true blocks all transmission (printf mode active).
     *
     * @param msg_type    one of the MSG_* defines from messages.h
     * @param payload     pointer to packed payload struct, or NULL
     * @param length      sizeof(your_struct), or 0 for zero-payload msgs
     */
    void SendPacket(uint8_t msg_type, const void *payload, uint8_t length);

    /*
     * ExecuteSafeStop — drive PB2 LOW immediately
     * PB2 LOW → NAND gate output HIGH → PCA9685 OE HIGH → all PWM off
     * Motors stop in hardware regardless of software state.
     */
    void ExecuteSafeStop();

    /*
     * ClearEStop — drive PB2 HIGH, re-enable motors
     * Call only after a fresh MSG_HEARTBEAT confirms link is restored.
     */
    void ClearEStop();

    /*
     * ToggleDebugMode — switch between binary (ROS) and printf mode
     * When true: SendPacket() is blocked, printf goes to USB via _write()
     * When false (default): binary frames sent, ROS can parse them
     * WARNING: never enable debug mode while ROS is connected
     */
    void ToggleDebugMode(bool enable);
    bool IsDebugMode() const { return debug_mode; }
    bool IsEStopActive() const { return estop_active; }

private:
    /* ── Ring buffer ──────────────────────────────────────────────── */
    static const uint16_t BUFFER_SIZE = 512;
    uint8_t rx_buffer[BUFFER_SIZE];
    volatile uint16_t head; /* written by ISR only       — must be volatile */
    uint16_t tail;          /* read/written by main loop — NOT volatile      */

    /* ── Parser state machine ─────────────────────────────────────── */
    enum ParseState
    {
        STATE_SYNC,    /* scanning for 0xFF                    */
        STATE_ID,      /* reading message type byte            */
        STATE_LEN,     /* reading payload length byte          */
        STATE_PAYLOAD, /* collecting payload_len bytes         */
        STATE_CRC      /* validating CRC, dispatching on match */
    };
    ParseState current_state;
    uint8_t active_msg_id;
    uint8_t active_msg_len;
    uint8_t payload_buffer[MAX_PAYLOAD_SIZE];
    uint8_t payload_index;

    /* ── Watchdog ─────────────────────────────────────────────────── */
    static constexpr uint32_t TIMEOUT_MS = 500;
    uint32_t last_heartbeat_tick;
    bool estop_active;

    /* ── Config ───────────────────────────────────────────────────── */
    bool debug_mode;
};

/* ── Global instance — extern'd in stm32_bridge.cpp ─────────────────── */
extern STM32Bridge g_bridge;

/* ── C-linkage functions — defined in stm32_bridge.cpp ──────────────── */
/*
 * These are declared here for .cpp files that include stm32_bridge.hpp.
 * bridge_c_api.h declares the same signatures for .c files.
 * Both declarations must match exactly.
 */
#ifdef __cplusplus
extern "C"
{
#endif

    void Bridge_Init(void);
    void Bridge_Update(void);
    void STM32Bridge_PushBytes(const uint8_t *buf, uint32_t len);

#ifdef __cplusplus
}
#endif

#endif /* STM32_BRIDGE_HPP */
 