road_detector:
  ros__parameters:
    camera_topic: "/camera/image_raw"
    camera_info_topic: "/camera/camera_info"
    output_pointcloud_topic: "/road_detector/pointcloud"
    output_lane_mask_topic: "/road_detector/debug/lane_mask"
    output_bev_topic: "/road_detector/debug/bev_image"
    output_costmap_topic: "/road_detector/stats"
    
    # Camera calibration
    camera_height: 1.43
    pitch_deg: -50.0
    yaw_deg: 0.0
    roll_deg: 0.0
    fx: 793.79768697 # final
    fy: 813.96117996 # final
    cx: 290.78702859 # final
    cy: 241.57106901 # final
    dist_coeffs: [-4.97661814e-01, 8.05356640e+00, 9.44660547e-03, -2.64434172e-02, -4.33974203e+01]
    
    # Detection parameters
    min_radius: 5
    max_radius: 200
    
    # Debug Options
    publish_debug_images: False
    publish_performance_stats: False

    # Point cloud parameters
    max_points_per_cloud: 10000
